### ISSUE TITLE
Replace music-metadata

### ISSUE THREAD

**Issue by Borewit** [motabass/motabass#1]
Hi @motabass, I am @Borewit, the author of [music-metadata-browser](https://github.com/Borewit/music-metadata-browser). 

I left a [small comment](https://github.com/motabass/motabass/commit/3c021fe989a25ca82d63e0b1648856d5f544ca19#r37362496), maybe you did notice it.

Although [jsmediatags](https://github.com/aadsm/jsmediatags) is a good parser as well, it is much more limited in functionality.

Can you please explain me why did [music-metadata-browser](https://github.com/Borewit/music-metadata-browser) not work for you @motabass?

Sorry to bother you, I look forward to your feedback. If you prefer a [chat](https://discord.gg/KyBr6sb).

**Comment by motabass** [comment]
Hi. I ran into a Problem with *global* being undefined. I Finally fixed it by adding the following to my polyfills.ts

JavaScript`(window as any).global = window;
global.Buffer = global.Buffer || require('buffer').Buffer;
(window as any).process = {
  version: ''
};`

**Comment by Borewit** [comment]
[music-metadata-browser](https://github.com/Borewit/music-metadata-browser), is using [music-metadata](https://github.com/Borewit/music-metadata) which is designed to work with any audio format, all metadata, able to combine metadata (in case of different tag headers), provide format information, stability, accuracy. That may cost a bit of extra time.

It depends a bit what type of audio files you read, and what the transport format is. In case of HTTP, it will run most likely much be faster if you enable RFC-7233 range, using [tokenizer-http](https://github.com/Borewit/tokenizer-http). Note that your server must able to handle these range request. [jsmediatags](https://github.com/aadsm/jsmediatags) does support RFC-7233 range out of the box.

**Comment by motabass** [comment]
I am getting files only from users local file system right now.

**Comment by Borewit** [comment]
> I am getting files only from users local file system right now.

In that case you should use [music-metadata](https://github.com/Borewit/music-metadata) directly and use [`parsefile()`](https://github.com/Borewit/music-metadata#parsefile-function). Should go pretty fast. Let me know if that worked for you.

**Comment by motabass** [comment]
Ok. I'll give it a try. Do i need any additional peerDependencies, like `buffer` or so,  to make it work in the browser? For music-metadata-browser i finally also had to add `stream` to my dependencies to make the angular production-build work.

**Comment by Borewit** [comment]
I am not sure, I did some tests with [audio-tag-analyzer](https://audio-tag-analyzer.netlify.com/) using `parseBlob()`.

In debug mode, using Google Chrome, Intel i7-7800X 3.5 GHz:

| file size | file type | duration      |
|-----------|-----------|---------------|
| ~28 MB    | FLAC file | ~400 ms       |
| ~8 MB     | m4a file  | ~40..180 ms   |
| 4..13 MB  | MP3 file  | ~80 ..165 ms  |

I just pushed these changes to the master, you can try for yourself here [audio-tag-analyzer](https://audio-tag-analyzer.netlify.com/).

**Comment by motabass** [comment]
I testet with my files on my computer in audio-tag-analyzer and i'm getting the same speeds as in my app...as expected. I will still go with music-metadata-browser just for the features and because i hav a cache  for metadata in my app. It would be nice if you could add some additional docs about which peer-dependencies and settings are required to make music-metadata-browser realy wwork in the browser. I had to dive into audio-tag-analyzer to find out what was missing in my app. See here: https://github.com/motabass/motabass/commit/1954880e463ca849a4ba06a91f740de40f90a1d9

**Comment by Borewit** [comment]
> It would be nice if you could add some additional docs about which peer-dependencies and settings are required to make music-metadata-browser realy wwork in the browser.

In principal all the requirements are listed in the [package.json](https://github.com/Borewit/music-metadata-browser/blob/master/package.json). It's Angular which fucks up, using an ancient buffer version and other dependencies which are deprecated.

I have seen it working with multiple module bundlers out of the box.

But I agree, it would be better if it would be all documented. But it takes time to investigate, and to maintain. Helps is very welcome, it's pure idealism to share of all this, I am not getting paid for it

**Comment by motabass** [comment]
With the latest Angular 10 and and music-metadata-browser 2.1.2 i don't need too add any node dependencies an resolutions anymore in package.json. Thats great.

Thanks for your work on this

**Comment by Borewit** [comment]
Thanks for your feedback, sounds good.
